### PR TITLE
[Animation] Flying Flame

### PR DESCRIPTION
**Pull request by ChasarooniZ**

### CODE REVIEW

**Comment by MrVauxs** [comment]
You can compress this much better by putting the options at the top. Duplicating everything just makes it more confusing.

**Comment by ChasarooniZ** [comment]
Kk I'll make the change when I get the time

**Comment by ChasarooniZ** [comment]
> You can compress this much better by putting the options at the top. Duplicating everything just makes it more confusing.

Fixed

**Comment by MrVauxs** [comment]
Dude
chrome_AuTMCMNTEp

**Pull request merged**
