### PR TITLE
[Animation] Divine Wrath

### PR DESCRIPTION
**Pull request by ChasarooniZ**

### CODE REVIEW

**Comment by MrVauxs** [comment]
Fix the changelog and it feels like the colors are all over the place?

**Comment by ChasarooniZ** [comment]
## Color Methodology
 - Holy - Yellow White
 - Neutral - Blue
 - Unholy - Black Purple
 ## Preview of animations
 
divineWrath-neutral
divineWrath-unholy
divineWrath-Holy

**Comment by MrVauxs** [comment]
Is this the same for the free version? That's where the confusion was mainly about.

**Comment by ChasarooniZ** [comment]
Yeah should be same idea, when I get a minute I'll share the preview of that.

Had to do more coloration work as they only have the yellow blue Color

**Comment by ChasarooniZ** [comment]
DivineWrath-free-Neutral
DivineWrath-free-Holy
DivineWrath-free-Unholy

**Comment by ChasarooniZ** [comment]
free Preview after I fixed some inheritance issues

**Comment by MrVauxs** [comment]
That's what I was wondering about. Nice.

**Pull request merged**
